
dist: trusty
sudo: false

language: node_js
node_js:
  - '12.12.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: aevusbv

cache:
  directories:
    - ./node_modules

before_script:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - npm install -g @angular/cli
  - npm install -g eslint

script:
  - npm run lint
  - npm run test
  - sonar-scanner -Dsonar.verbose=true -X
  - ng build --prod --base-href https://github.com/AevusBV/QTime-frontend/
