
dist: trusty
sudo: false

language: node_js
node_js:
  - '12.12.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run lint
  - npm run test
  - ng build --prod --base-href https://github.com/AevusBV/QTime-frontend/
